// config/mouse_layer.keymap.inc

&keymap {
  u_mouse {
    bindings = <
      U_BTN1       U_BTN2       U_BTN3       U_BTN4       U_BTN5
      U_MH_LEFT    U_MH_DOWN    U_MH_UP      U_MH_RIGHT   U_NA
      U_MW_LEFT    U_MW_DOWN    U_MW_UP      U_MW_RIGHT   U_NA
      U_NA         U_NA         U_NA         U_NA         U_NA
      U_NA         U_NA         U_NA         U_NA         U_NA
      U_NA         U_NA         U_NA
      U_NA         U_NA         U_NA
      U_NA         U_NA         U_NA
    >;
  };
};
