# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Auto Build Totem'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-green:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy GREEN config
        run: cp config/totem-green.conf config/totem.conf
      - name: Build GREEN
        uses: ./.github/workflows/main.yml
        with:
          board: '["seeeduino_xiao_ble"]'
          shield: '["totem_left","totem_right"]'
          alphas: '["default"]'
          nav: '["default"]'
          layers: '["default"]'
          mapping: '["default"]'
          custom_config: '["default"]'
          kconfig: '["default"]'
          branches: '["default"]'
          modules: '["default"]'
        
  build-kh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy KH config
        run: cp config/totem-kh.conf config/totem.conf
      - name: Build KH
        uses: ./.github/workflows/main.yml
        with:
          board: '["seeeduino_xiao_ble"]'
          shield: '["totem_left","totem_right"]'
          alphas: '["default"]'
          nav: '["default"]'
          layers: '["default"]'
          mapping: '["default"]'
          custom_config: '["default"]'
          kconfig: '["default"]'
          branches: '["default"]'
          modules: '["default"]'
          
  build-wn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy WN config
        run: cp config/totem-wn.conf config/totem.conf
      - name: Build WN
        uses: ./.github/workflows/main.yml
        with:
          board: '["seeeduino_xiao_ble"]'
          shield: '["totem_left","totem_right"]'
          alphas: '["default"]'
          nav: '["default"]'
          layers: '["default"]'
          mapping: '["default"]'
          custom_config: '["default"]'
          kconfig: '["default"]'
          branches: '["default"]'
          modules: '["default"]'
