name: Test Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # ⇣ comment-out or delete this guard so the job isn't skipped
    # if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left","totem_right"]'
